# basic options
title: Vakantie Oktober 2018 - Duitsland
author: Kees
description: Blog van de vakantie van Oktober 2018
baseurl: "2018-10-vakantie-duitsland" 
url: "https://prudento-nl.github.io" 

images: "https://prudento-nl.github.io/2018-10-vakantie-duitsland/images"

# Build settings
markdown: kramdown
theme: minima

minima:
  date_format: "%d-%m-%Y"
